import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TaskProvider } from "@/lib/task-context";
import { AuthProvider } from "@/lib/auth-context";

import { SidebarProvider } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("================================================");
  console.log("Current env is", process.env.NEXT_PUBLIC_APP_ENV);
  console.log("================================================");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <TaskProvider>
            <SidebarProvider>
              {/* <AppSidebar /> */}
              <main className="flex-1 overflow-hidden">{children}</main>
            </SidebarProvider>
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
